---
Name: gridfield-rich-filter-header
---
SilverStripe\Forms\FormRequestHandler:
  extensions:
    - Terraformers\RichFilterHeader\Extension\GridFieldRichFilterHeaderRequestExtension
  url_handlers:
    'field/$FieldName!': 'handleFieldComposite'
